# Generated by Django 5.1.3 on 2024-11-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsechoice',
            old_name='text',
            new_name='choices_text',
        ),
    ]
