# Generated by Django 5.1.3 on 2024-11-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_questiontype_question_question_question_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.questiontype'),
        ),
    ]
