# Generated by Django 5.1.3 on 2024-12-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_text_responsechoice_choices_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsechoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
