# Generated by Django 5.1.3 on 2024-12-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
