# Generated by Django 5.1.3 on 2024-11-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedsurvey',
            old_name='survey',
            new_name='survey_id',
        ),
        migrations.AddField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.survey'),
        ),
    ]
