# Generated by Django 5.1.4 on 2024-12-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_respoint_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='respoint_by_user',
        ),
    ]
